Link2Web/Areas/Admin/Controllers/SettingTypesController.cs
using Link2Web.Areas.Admin.Models;
using Link2Web.Controllers;
using Link2Web.DAL;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Link2Web.Areas.Admin.Controllers
{
    public class SettingTypesController : BaseController
    {
        private Link2WebDbContext db = new Link2WebDbContext();

        // GET: Admin/SettingTypes
        public ActionResult Index()
        {
            return View(db.SettingTypes.ToList());
        }

        // GET: Admin/SettingTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SettingType settingType = db.SettingTypes.Find(id);
            if (settingType == null)
            {
                return HttpNotFound();
            }
            return View(settingType);
        }

        // GET: Admin/SettingTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/SettingTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SettingTypeId,Type,Visible")] SettingType settingType)
        {
            if (ModelState.IsValid)
            {
                db.SettingTypes.Add(settingType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(settingType);
        }

        // GET: Admin/SettingTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SettingType settingType = db.SettingTypes.Find(id);
            if (settingType == null)
            {
                return HttpNotFound();
            }
            return View(settingType);
        }

        // POST: Admin/SettingTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SettingTypeId,Type,Visible")] SettingType settingType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(settingType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(settingType);
        }

        // GET: Admin/SettingTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SettingType settingType = db.SettingTypes.Find(id);
            if (settingType == null)
            {
                return HttpNotFound();
            }
            return View(settingType);
        }

        // POST: Admin/SettingTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SettingType settingType = db.SettingTypes.Find(id);
            db.SettingTypes.Remove(settingType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Link2Web/Areas/Admin/Views/SettingTypes/Create.cshtml
@model Link2Web.Areas.Admin.Models.SettingType

@{
    ViewBag.Title = "Create";
}

<div id="main">

    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="col-md-12 col-sm-12 col-xs-12 personal-info">

            <div class="form-group row">
                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Visible, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="checkbox col-md-10 col-sm-9 col-xs-12">
                    @Html.CheckBoxFor(model => model.Visible, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.Visible, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-12">
                    <input type="submit" class="btn btn-primary" value="Save Changes">
                    <span></span>
                    <input type="reset" class="btn btn-default" value="Cancel">
                </div>
            </div>
        </div>

    }

</div>

Link2Web/Areas/Admin/Views/SettingTypes/Delete.cshtml
@model Link2Web.Areas.Admin.Models.SettingType

@{
    ViewBag.Title = "Delete";
}

<span id="main">

    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>SettingType</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    </span>

Link2Web/Areas/Admin/Views/SettingTypes/Details.cshtml
@model Link2Web.Models.SettingType

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SettingType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SettingTypeId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Link2Web/Areas/Admin/Views/SettingTypes/Edit.cshtml
@model Link2Web.Areas.Admin.Models.SettingType

@{
    ViewBag.Title = "Edit";
}

<div id="main">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SettingTypeId)

        <div class="form-group row">
            @Html.LabelFor(model => model.Type, htmlAttributes: new {@class = "control-label col-md-2 col-sm-3 col-xs-12"})
            <div class="col-md-10 col-sm-9 col-xs-12">
                @Html.EditorFor(model => model.Type, new {htmlAttributes = new {@class = "form-control col-md-9 col-xs-12"}})
                @Html.ValidationMessageFor(model => model.Type, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Visible, htmlAttributes: new {@class = "control-label col-md-2 col-sm-3 col-xs-12"})
            <div class="checkbox col-md-10 col-sm-9 col-xs-12">
                @Html.CheckBoxFor(model => model.Visible, new {htmlAttributes = new {@class = "form-control col-md-9 col-xs-12"}})
                @Html.ValidationMessageFor(model => model.Visible, "", new {@class = "text-danger"})
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

Link2Web/Areas/Admin/Views/SettingTypes/Index.cshtml
@model IEnumerable <Link2Web.Areas.Admin.Models.SettingType>

@{
    ViewBag.Title = "Index";
}

<div id="main">

    <h2>Setting types</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    <div class="container" id="gridList">
        <!--Row with two equal columns-->
        <div class="row" id="gridHeader">
            <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">@Resources.Resources.Type</div>
            <div class="col-xs-hide col-sm-hide col-md-4 col-lg-4">@Resources.Resources.Visible</div>
            <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4"></div>
        </div>

        @foreach (var item in Model.ToList())
        {
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">@Html.DisplayFor(modelItem => item.Type)</div>
                <div class="col-xs-hide col-sm-hide col-md-hide col-lg-4">@Html.DisplayFor(modelItem => item.Visible)</div>
                <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">
                    <a class="lnk-space" href='@Url.Action("Edit", "SettingTypes", new {id = item.SettingTypeId})'>
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    </a>
                    <a href='@Url.Action("Delete", "SettingTypes", new {id = item.SettingTypeId})'>
                        <span class="glyphicon glyphicon-remove"></span> Delete
                    </a>
                </div>
            </div>
        }

    </div>
</div>