Link2Web/Areas/Admin/Models/LinkType.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Link2Web.Areas.Admin.Models
{
    public class LinkType
    {
        [ReadOnly(true)]
        public int LinkTypeId { get; set; }
        [Display(Name = "Type", ResourceType = typeof(Resources.Resources))]
        [Required]
        public string Type { get; set; }
        [Display(Name = "Visible", ResourceType = typeof(Resources.Resources))]
        [DefaultValue(true)]
        public bool Visible { get; set; }
    }
}

Link2Web/Models/Link.cs
using Link2Web.Areas.Admin.Models;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace Link2Web.Models
{
    public class Link
    {

        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        [Required]
     
        public int LinkId { get; set; }
        public string UserId { get; set; }

        [Display(Name = "Status", ResourceType = typeof(Resources.Resources))]
        [HiddenInput(DisplayValue = false)]

        public LinkStatus StatusId { get; set; }
        [HiddenInput(DisplayValue = false)]

        [Required]

        [Display(Name = "LinkType", ResourceType = typeof(Resources.Resources))]
        public int LinkTypeId { get; set; }

        [Display(Name = "Contact", ResourceType = typeof(Resources.Resources))]
        [HiddenInput(DisplayValue = false)]
        public int ContactId { get; set; }


        [Display(Name = "Project", ResourceType = typeof(Resources.Resources))]
        [HiddenInput(DisplayValue = false)]
        public int ProjectId { get; set; }

        [Display(Name = "WebsiteUrl", ResourceType = typeof (Resources.Resources))]
        [Required(ErrorMessageResourceType = typeof(Resources.Resources),
            ErrorMessageResourceName = "IsRequired")]
        public string WebsiteUrl { get; set; }

        [Display(Name = "AnchorText", ResourceType = typeof (Resources.Resources))]
        [MaxLength(40, ErrorMessage = @"AnchorText cannot be longer than 40 characters.")]
        [Required(ErrorMessageResourceType = typeof(Resources.Resources),
            ErrorMessageResourceName = "IsRequired")]
        public string AnchorText { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources.Resources),
            ErrorMessageResourceName = "IsRequired")]
        [Display(Name = "DestinationUrl", ResourceType = typeof (Resources.Resources))]
        public string DestinationUrl { get; set; }

        [Display(Name = "Description", ResourceType = typeof (Resources.Resources))]
        public string Description { get; set; }
        [HiddenInput(DisplayValue = false)]
        [ScaffoldColumn(false)]

        [Display(Name = "CreatedOn", ResourceType = typeof (Resources.Resources))]
        public DateTime CreatedOn { get; set; }

        [Display(Name = "BacklinkFound", ResourceType = typeof (Resources.Resources))]
        [DefaultValue(false)]
        public bool BacklinkFound { get; set; }
        public virtual Country Countries { get; set; }


        public Link()
        {
            CreatedOn = DateTime.Now;
        }
    }
}

Link2Web/Models/LinkType.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Link2Web.Models
{
    public class LinkType
    {
        [ReadOnly(true)]
        public int LinkTypeId { get; set; }
        [Display(Name = "Type", ResourceType = typeof(Resources.Resources))]
        [Required]
        public string Type { get; set; }
        [Display(Name = "Visible", ResourceType = typeof(Resources.Resources))]
        [DefaultValue(true)]
        public bool Visible { get; set; }

        public ICollection<Link> Links { get; set; }
    }
}

Link2Web/Controllers/LinksController.cs
using DataTables.Mvc;
using Link2Web.DAL;
using Link2Web.DAL.Repositories;
using Link2Web.Models;
using Link2Web.ViewModels;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;

namespace Link2Web.Controllers
{
    public class LinksController : BaseController
    {
        private ILinkRepository _context;
        private IContactRepository _contactsContext;
        private ILinkTypeRepository _linkTypeContext;
        private IProjectRepository _projectContext;

        public LinksController()
        {
            _context = new LinkRepository(new Link2WebDbContext());
            _contactsContext = new ContactRepository(new Link2WebDbContext());
            _linkTypeContext = new LinkTypeRepository(new Link2WebDbContext());
            _projectContext = new ProjectRepository(new Link2WebDbContext());


            Mail.Host = "smtp.gmail.com";
            Mail.Username = "ivolink2web@gmail.com";
            Mail.Password = "#IVO#2017";
            Mail.Port = 587;
            Mail.SSL = true;
        }

        // GET: Links
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            return View(_context.GetLinks().Where(l => l.ProjectId == (int)Session["ProjectId"] && l.UserId.Equals(userId)));
        }

        // GET: Links/Details/5
        public ActionResult Details(int id)
        {
            var userId = User.Identity.GetUserId();
            Link link = _context.GetLinkById(id, userId);

            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        // GET: Links/Create
        public ActionResult Create()
        {
            var userId = User.Identity.GetUserId();

            ViewBag.ProjectId = new SelectList(_projectContext.GetProjects().Where(p => p.UserId.Equals(userId)), "ProjectId", "Name");
            ViewBag.ContactId = new SelectList(_contactsContext.GetContacts().Where(c => c.UserId.Equals(userId)), "ContactId", "Name");
            ViewBag.LinkTypeId = new SelectList(_linkTypeContext.GetLinkTypes(), "LinkTypeId", "Type");

            return View();
        }

        // POST: Links/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(
                Include =
                    "ProjectId,LinkId,UserId,WebsiteUrl,AnchorText,DestinationUrl,Description,CreatedOn,ContactId,LinkTypeId"
                )] Link
                link)
        {

            var userId = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                link.UserId = User.Identity.GetUserId();
                _context.InsertLink(link);
                _context.Save();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectId = new SelectList(_projectContext.GetProjects().Where(p => p.UserId.Equals(userId)), "ProjectId", "Name", link.ProjectId);
            ViewBag.ContactId = new SelectList(_contactsContext.GetContacts().Where(c => c.UserId.Equals(userId)), "ContactId", "Name", link.ContactId);
            ViewBag.LinkTypeId = new SelectList(_linkTypeContext.GetLinkTypes(), "LinkTypeId", "Type", link.LinkTypeId);

            return View(link);
        }

        // GET: Links/Edit/5
        public ActionResult Edit(int id)
        {
            var userId = User.Identity.GetUserId();
            Link link = _context.GetLinkById(id, userId);

            if (link == null)
            {
                return HttpNotFound();
            }

            ViewBag.ProjectId = new SelectList(_projectContext.GetProjects().Where(p => p.UserId.Equals(userId)), "ProjectId", "Name", link.ProjectId);
            ViewBag.ContactId = new SelectList(_contactsContext.GetContacts().Where(c => c.UserId.Equals(userId)), "ContactId", "Name", link.ContactId);
            ViewBag.LinkTypeId = new SelectList(_linkTypeContext.GetLinkTypes(), "LinkTypeId", "Type", link.LinkTypeId);

            return View(link);
        }

        // POST: Links/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "ProjectId,LinkId,WebsiteUrl,AnchorText,DestinationUrl,Description,CreatedOn,ContactId,LinkTypeId")] Link link)
        {
            var userId = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                link.UserId = User.Identity.GetUserId();
                _context.UpdateLink(link);
                _context.Save();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectId = new SelectList(_projectContext.GetProjects().Where(p => p.UserId.Equals(userId)), "ProjectId", "Name", link.ProjectId);
            ViewBag.ContactId = new SelectList(_contactsContext.GetContacts().Where(c => c.UserId.Equals(userId)), "ContactId", "Name", link.ContactId);
            ViewBag.LinkTypeId = new SelectList(_linkTypeContext.GetLinkTypes(), "LinkTypeId", "Type", link.LinkTypeId);

            return View(link);
        }

        // GET: Links/Delete/5
        public ActionResult Delete(int id)
        {
            var userId = User.Identity.GetUserId();
            Link link = _context.GetLinkById(id, userId);

            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        // POST: Links/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _context.DeleteLink(id);
            _context.Save();
            return RedirectToAction("Index");
        }

        public JsonResult GetLinks([ModelBinder(typeof (DataTablesBinder))] IDataTablesRequest requestModel)
        {
            var userId = User.Identity.GetUserId();
            var links =
                _context.GetLinks().Select(l => new {l.LinkId, l.AnchorText, l.WebsiteUrl, l.Description, l.UserId, l.ProjectId})
                    .Where(l => l.UserId.Equals(userId) && l.ProjectId == (int)Session["ProjectId"])
                    .ToList();

            // Apply filters
            if (requestModel.Search.Value != string.Empty)
            {
                var value = requestModel.Search.Value.Trim();

                links =
                    links.Where(
                        l =>
                            l.AnchorText.Contains(value) || l.WebsiteUrl.Contains(value) ||
                            l.Description.Contains(value)).ToList();
            }

            var filteredCount = links.Count();

            // Sort
            var sortedColumns = requestModel.Columns.GetSortedColumns();
            var orderByString = string.Empty;

            foreach (var column in sortedColumns)
            {
                orderByString += orderByString != string.Empty ? "," : "";
                orderByString += (column.Data == "WebsiteUrl" ? "WebsiteUrl" : column.Data) +
                                 (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
            }

            links = links.OrderBy(orderByString == string.Empty ? "WebsiteUrl asc" : orderByString).ToList();

            // links
            links = links.Skip(requestModel.Start).Take(requestModel.Length).ToList();


            return Json(new DataTablesResponse(requestModel.Draw, links, filteredCount, links.Count),
                JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SendMail(MailViewModel model)
        {
            var smtp = new SmtpClient
            {
                Host = Mail.Host,
                Port = Mail.Port,
                EnableSsl = Mail.SSL,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(Mail.Username, Mail.Password)
            };

            using (var message = new MailMessage(Mail.Username, Mail.Password))
            {
                message.Subject = model.Subject;
                message.Body = model.Body;
                message.IsBodyHtml = false;
                smtp.Send(message);
            }

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
            base.Dispose(disposing);
        }
    }
}

Link2Web/Views/Links/Create.cshtml
@model Link2Web.Models.Link

@{
    ViewBag.Title = "Add Link";
}

<span id="main">
    <h2>Add Link</h2>

    @using (@Html.BeginForm(null, null, FormMethod.Post, new { name = "frmCreateLink", id = "frmCreateLink", @data_toggle = "validator" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="col-md-12 col-sm-12 col-xs-12 personal-info">
            <div class="form-group row">
                @Html.LabelFor(model => model.ProjectId, htmlAttributes: new {@class = "control-label col-md-2 col-sm-3 col-xs-12"})
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.DropDownList("ProjectId", null, htmlAttributes: new {@class = "form-control col-md-9 col-xs-12"})
                    @Html.ValidationMessageFor(model => model.ProjectId, "", new {@class = "text-danger"})
                </div>
            </div>
            
            <div class="form-group row">
                @Html.LabelFor(model => model.ContactId, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.DropDownList("ContactId", null, htmlAttributes: new { @class = "form-control col-md-9 col-xs-12" })
                    @Html.ValidationMessageFor(model => model.ContactId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.WebsiteUrl, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.EditorFor(model => model.WebsiteUrl, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.WebsiteUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.AnchorText, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.EditorFor(model => model.AnchorText, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.AnchorText, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.DestinationUrl, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.EditorFor(model => model.DestinationUrl, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.DestinationUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Description, htmlAttributes: new {@class = "control-label col-md-2 col-sm-3 col-xs-12"})
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control col-md-9 col-xs-12"}})
                    @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                </div>
            </div>
            
            <div class="form-group row">
                @Html.LabelFor(model => model.LinkTypeId, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.DropDownList("LinkTypeId", null, htmlAttributes: new { @class = "form-control col-md-9 col-xs-12" })
                    @Html.ValidationMessageFor(model => model.LinkTypeId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-12">
                    <input type="submit" class="btn btn-primary" value="Save Changes">
                    <span></span>
                    <input type="reset" class="btn btn-default" value="Cancel">
                </div>
            </div>
        </div>
    }

    </span>


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Link2Web/Views/Links/Delete.cshtml
@model Link2Web.Models.Link

@{
    ViewBag.Title = "Delete";
}

<span id="main">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Link</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Project.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Project.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LinkId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LinkId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.WebsiteUrl)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WebsiteUrl)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AnchorText)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AnchorText)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DestinationUrl)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DestinationUrl)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedOn)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    </span>

Link2Web/Views/Links/Details.cshtml
@model Link2Web.Models.Link

@{
    ViewBag.Title = "Details";
}

<span id="main">
    <h2>Details</h2>

    <div>
        <h4>Link</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Project.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Project.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LinkId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LinkId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.WebsiteUrl)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WebsiteUrl)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AnchorText)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AnchorText)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DestinationUrl)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DestinationUrl)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedOn)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ProjectId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
    </span>

Link2Web/Views/Links/Edit.cshtml
@model Link2Web.Models.Link

@{
    ViewBag.Title = "Edit";
}

<div id="main">
    <h2>Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.LinkId)


        <div class="col-md-12 col-sm-12 col-xs-12 personal-info">
            <div class="form-group row">
                @Html.LabelFor(model => model.ProjectId, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control col-md-9 col-xs-12" })
                    @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.ContactId, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.DropDownList("ContactId", null, htmlAttributes: new { @class = "form-control col-md-9 col-xs-12" })
                    @Html.ValidationMessageFor(model => model.ContactId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.WebsiteUrl, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.EditorFor(model => model.WebsiteUrl, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.WebsiteUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.AnchorText, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.EditorFor(model => model.AnchorText, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.AnchorText, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.DestinationUrl, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.EditorFor(model => model.DestinationUrl, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.DestinationUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.LinkTypeId, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.DropDownList("LinkTypeId", null, htmlAttributes: new { @class = "form-control col-md-9 col-xs-12" })
                    @Html.ValidationMessageFor(model => model.LinkTypeId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-12">
                    <input type="submit" class="btn btn-primary" value="Save Changes">
                    <span></span>
                    <input type="reset" class="btn btn-default" value="Cancel">
                </div>
            </div>
        </div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    
</div>

Link2Web/Views/Links/GetEmailForm.cshtml
@model Link2Web.Models.Mail

@{
    ViewBag.Title = "Send mail to " + Model.ToEmail;
}

<span id="main">

    <h2>Create Mail</h2>
    <hr />


    @using (Html.BeginForm("SendMail", "Links", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="col-md-12 col-sm-12 col-xs-12 personal-info" id="mailModal">

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 alert alert-success alert-dismissible fade in">
                    Details
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.ToEmail, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.EditorFor(model => model.ToEmail, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.ToEmail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group row">
                @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2 col-sm-3 col-xs-12" })
                <div class="col-md-10 col-sm-9 col-xs-12">
                    @Html.TextAreaFor(model => model.Body, new { htmlAttributes = new { @class = "form-control col-md-9 col-xs-12" } })
                    @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-12">
                    <input type="submit" class="btn btn-primary" value="Save Changes">
                    <span></span>
                    <input type="reset" class="btn btn-default" value="Cancel">
                </div>
            </div>
        </div>
    }
    </span>